name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Select and save the best model
      run: |
        python main.py

    - name: Deploy
      if: success()
      run: |
        best_model=$(cat best_model.txt)
        echo "Deploying application with the best model: $best_model"
        # Add your deployment commands here